return {
	gitcommitOverflow = { colors.base08, nil, nil, nil },
	gitcommitSummary = { colors.base0B, nil, nil, nil },
	gitcommitComment = { colors.base03, nil, nil, nil },
	gitcommitUntracked = { colors.base03, nil, nil, nil },
	gitcommitDiscarded = { colors.base03, nil, nil, nil },
	gitcommitSelected = { colors.base03, nil, nil, nil },
	gitcommitHeader = { colors.base0E, nil, nil, nil },
	gitcommitSelectedType = { colors.base0D, nil, nil, nil },
	gitcommitUnmergedType = { colors.base0D, nil, nil, nil },
	gitcommitDiscardedType = { colors.base0D, nil, nil, nil },
	gitcommitBranch = { colors.base09, nil, "bold", nil },
	gitcommitUntrackedFile = { colors.base0A, nil, nil, nil },
	gitcommitUnmergedFile = { colors.base08, nil, "bold", nil },
	gitcommitDiscardedFile = { colors.base08, nil, "bold", nil },
	gitcommitSelectedFile = { colors.base0B, nil, "bold", nil },
	DiffAdd = { colors.base0B, nil, nil, nil },
	DiffChange = { colors.base0C, colors.base00, nil, nil },
	DiffDelete = { colors.base08, nil, nil, nil },
	DiffText = { colors.base0D, nil, nil, nil },
	DiffAdded = { colors.base0B, colors.base00, nil, nil },
	DiffFile = { colors.base08, colors.base00, nil, nil },
	DiffNewFile = { colors.base0B, colors.base00, nil, nil },
	DiffLine = { colors.base0D, colors.base00, nil, nil },
	DiffRemoved = { colors.base08, colors.base00, nil, nil },
}
