#!/bin/sh

# variables
mod="Mod4"
term="alacritty"
browser="brave"

# repeat rate for key holding
riverctl set-repeat 50 300

# applications 
riverctl map normal $mod Return spawn $term
riverctl map normal $mod b spawn $browser

# general
riverctl map normal $mod+Shift Q exit
riverctl map normal $mod c close
riverctl map normal $mod f toggle-fullscreen
riverctl map normal $mod t toggle-float
riverctl map normal $mod m zoom 

# window swapping and focusing
riverctl map normal $mod j focus-view next
riverctl map normal $mod k focus-view previous
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# window resizing
riverctl map normal $mod h send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod l send-layout-cmd rivertile "main-ratio +0.05"

# number of main windows
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# workspace
for i in $(seq 1 7)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Control $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# mouse
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
