#!/bin/sh

### MISCELLANEOUS ###

riverctl declare-mode passthrough
riverctl set-repeat 50 300

### END OF MISCELLANEOUS ###

### MAPPINGS ###

riverctl map normal Super+Shift Q exit
riverctl map normal Super C close
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map normal Super T toggle-float

riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"

riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

riverctl map normal Super Space spawn dmenu_run
riverctl map normal Super Return spawn alacritty
riverctl map normal Super R spawn ~/.config/river/reload-waybar
riverctl map normal Super B spawn brave
riverctl map normal Super D spawn discord
riverctl map normal Super S spawn spotify
riverctl map normal Super G spawn steam

for i in $(seq 1 6)
do
    tags=$((1 << (i - 1)))

    riverctl map normal Super "$i" set-focused-tags $tags
    riverctl map normal Super+Shift "$i" set-view-tags $tags
    riverctl map normal Super+Control "$i" toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags $tags
done

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # the third parameter of 'wpctl' is the device id
    # to find the correct device id use the command 'wpctl status'
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-volume @DEFAULT_SINK@ 0%'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # 'light' will only work when executed as a super user or a user in the 'video' group
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

### END OF MAPPINGS ###

### STYLING ###

riverctl spawn waybar
riverctl spawn "swaybg -i ~/.config/river/wallpaper.jpg"
riverctl spawn blueman-applet
riverctl spawn "nm-applet --indicator"

riverctl border-color-focused 0xf5c2e7ee
riverctl border-color-unfocused 0x585b70aa

riverctl float-filter-add app-id float
riverctl float-filter-remove app-id spotify
riverctl float-filter-add app-id Tk
riverctl float-filter-add app-id Rofi

riverctl default-layout rivertile
rivertile -view-padding 10 -outer-padding 10

### END OF STYLING ###
