require('plugins')
require('globals')
require('settings')
require('keymappings')
require('colorscheme')

require('compe-conf')
require('galaxyline-conf')
require('dashboard-conf')
require('treesitter-conf')
require('telescope-conf')
require('nvimtree-conf')
require('vimwiki-conf')
require('goyo-conf')
require('floaterm-conf')
require('gitsigns-conf')

-- LSP
require('lsp')
require('lsp.clangd')
require('lsp.php-ls')
require('lsp.dart-ls')
require('lsp.lua-ls')
require('lsp.bash-ls')
require('lsp.go-ls')
require('lsp.js-ts-ls')
require('lsp.python-ls')
require('lsp.rust-ls')
require('lsp.json-ls')
require('lsp.yaml-ls')
require('lsp.terraform-ls')
require('lsp.vim-ls')
require('lsp.graphql-ls')
require('lsp.docker-ls')
require('lsp.html-ls')
require('lsp.css-ls')
require('lsp.emmet-ls')
require('lsp.efm-general-ls')
require('lsp.latex-ls')
require('lsp.svelte-ls')
require('lsp.tailwindcss-ls')
require('lsp.ruby-ls')
require('lsp.kotlin-ls')

