(use-package autothemer)
(use-package doom-themes)

(require 'autothemer)
(require 'doom-themes)

(autothemer-deftheme
 lunar "@ChristianChiarulli had made a Lunar theme for vim which is what I based my editor around. So I brought it to Emacs, mostly!"

 ((((class color) (min-colors #xFFFFFF)))

  (fg                   "#ABB2BF")
  (bg                   "#232731")
  (cursor_fg            "#515052")
  (cursor_bg            "#AEAFAD")

  (red                  "#BF616A")
  (green                "#A3BE8C")
  (yellow               "#E7cb93")
  (orange               "#c68a75")
  (grey                 "#9BA1AB")
  (blue                 "#5e81ac")
  (cyan                 "#88c0d0")
  (purple               "#B48EAD")
  (white                "#D8DEE9")
  (black                "#3b4252")

  (error_red            "#F44747")
  (light_green          "#B5CEA8")
  (dark_yellow          "#D7BA7D")
  (grey_blue            "#81A1C1")
  (light_blue           "#88C0D0")
  (vivid_blue           "#4FC1FF")
  (line_grey            "#5C6370")
  (cursor_grey          "#2C323C")
  (visual_grey          "#3E4452")
  (menu_grey            "#434C5E")
  (special_grey         "#3B4048")
  (warning_orange       "#ff8800")
  (info_yellow          "#FFCC66")
  (search_blue          "#1da1f2")
  (git_green            "#81B88B")
  (grey_alt             "#6A6E7E")

  (vertsplit            "#4C566A")
  (symlink              "#29B8D8")
  (executable           "#23D18B")
  (tabfill              "#292D38")
  (indentlinehighlight  "#767A8B")

  (comment              "#4c566a")
  (constant             yellow)
  (function_name        yellow)
  (string               green)
  (type                 purple)
  (boolean              orange)
  (keyword              blue)
  (modeline             (doom-darken bg 0.20))
  (builtin              yellow)
  (line_numbers         grey_alt)
  (current_line_number  white)
  (number               "#b5cea8")
  (highlight_line       (doom-darken bg 0.17))
  (ivy_hl_cur_line      (doom-darken bg 0.30))
  (org_source_bg        (doom-darken bg 0.10))
  (doc_strings          grey_alt)
  (lsp_face_hl          "#464646")
  (company_bg           "#4C566A")
  (company_alt_bg       (doom-darken company_bg 0.15)))

 ((default                      (:foreground fg :background bg))
  (fringe                       (:background bg))
  (cursor                       (:foreground cursor_fg :background cursor_bg))
  (region                       (:background visual_grey))
  (font-lock-keyword-face       (:foreground keyword))
  (font-lock-constant-face      (:foreground constant))
  (font-lock-string-face        (:foreground string))
  (font-lock-type-face          (:foreground type))
  (font-lock-comment-face       (:foreground comment))
  (font-lock-builtin-face       (:foreground builtin))
  (font-lock-function-name-face (:foreground function_name))
  (font-lock-variable-name-face (:foreground fg))
  (font-lock-doc-face           (:foreground doc_strings))
  (line-number                  (:foreground line_numbers))
  (line-number-current-line     (:foreground current_line_number :background highlight_line :weight 'bold))
  (hl-line                      (:background highlight_line))
  (show-paren-match             (:foreground error_red :weight 'extra-bold :underline t))
  (show-paren-mismatch          (:foreground warning_orange :weight 'extra-bold))
  (highlight-numbers-number     (:foreground number))
  (evil-ex-search               (:background grey))

  ;; modeline
  (mode-line                        (:foreground fg :background modeline))
  (mode-line-inactive               (:background modeline))
  (doom-modeline-evil-normal-state  (:foreground blue :weight 'bold))
  (doom-modeline-evil-insert-state  (:foreground green :weight 'bold))
  (doom-modeline-evil-visual-state  (:foreground red :weight 'bold))
  (doom-modeline-evil-emacs-state   (:foreground grey :weight 'bold))
  (doom-modeline-bar                (:background blue))
  (doom-modeline-lsp-error          (:foreground error_red))
  (doom-modeline-lsp-warning        (:foreground warning_orange))
  (doom-modeline-lsp-success        (:foreground green))
  (doom-modeline-lsp-running        (:foreground blue))
  (doom-modeline-info               (:foreground "#ffcc66"))
  (doom-modeline-warning            (:foreground "#f44747"))
  (doom-modeline-error              (:foreground "#ff8800"))
  (doom-modeline-urgent             (:foreground "#94151b"))

  ;; flymake
  (flymake-note                     (:foreground "#ffcc66" :underline t))
  (flymake-error                    (:foreground "#f44747" :underline t))
  (flymake-warning                  (:foreground "#ff8800" :underline t))

  ;; org
  (org-level-1              (:foreground green :weight 'bold))
  (org-level-2              (:foreground purple :weight 'bold))
  (org-level-3              (:foreground blue :weight 'bold))
  (org-level-4              (:foreground green :weight 'bold))
  (org-level-5              (:foreground purple :weight 'bold))
  (org-level-6              (:foreground blue :weight 'bold))
  (org-level-7              (:foreground green :weight 'bold))
  (org-level-8              (:foreground purple :weight 'bold))
  (org-document-info-keyword    (:foreground grey))
  (org-document-title           (:foreground blue :weight 'bold))
  (org-document-info            (:foreground blue :weight 'bold))
  (org-block                    (:foreground fg :background org_source_bg))

  ;; ivy
  (ivy-highlight-face           (:foreground blue))
  (ivy-current-match            (:background ivy_hl_cur_line))
  (ivy-minibuffer-match-face-1  (:foreground blue))
  (ivy-minibuffer-match-face-2  (:foreground blue))
  (ivy-minibuffer-match-face-3  (:foreground blue))
  (ivy-minibuffer-match-face-4  (:foreground blue))

  ;; lsp
  (lsp-face-highlight-write     (:foreground fg :background lsp_face_hl :weight 'bold))
  (lsp-face-highlight-read      (:foreground fg :background lsp_face_hl :weight 'bold))
  (lsp-ui-doc-background        (:background highlight_line))

  ;; company
  (company-scrollbar-bg                 (:background company_alt_bg))
  (company-scrollbar-fg                 (:background white))
  (company-box-scrollbar                (:background white))
  (company-preview                      (:foreground company_bg))
  (company-preview-common               (:foreground white))
  (company-preview-search               (:background company_bg))
  (company-tooltip                      (:background company_bg))
  (company-tooltip-common               (:foreground white))
  (company-tooltip-common-selection     (:foreground white))
  (company-tooltip-annotation           (:foreground white))
  (company-tooltip-annotation-selection (:foreground white))
  (company-tooltip-selection            (:background blue))
  (company-tooltip-mouse                (:background blue :foreground nil))

  ;; git gutter
  (git-gutter:added             (:foreground "#587c0c"))
  (git-gutter:deleted           (:foreground "#94151b"))
  (git-gutter:modified          (:foreground "#0c7d9d"))

  ))

(provide-theme 'lunar)

